clientConnection:
  kubeconfig: /etc/loxilight/loxi-agent.kubeconfig
hostProcPathPrefix: "/"
loxiEndpointIface: "hsbond1"
tunnelIP: "100.1.1.2/24"
# localIP: "2.2.2.2/24"
flowCollectorProto: "tcp"
flowCollectorAddr: "118.67.131.101:30473"
loxilightIP: "tcp://192.168.20.81:8861"
withSmartNIC: true
---
apiVersion: v1
kind: ConfigMap
data:
  loxi-agent.conf: |
    featureGates:
    FlowExporter: true
    flowPollInterval: "5s"
    activeFlowExportTimeout: "60s"
    idleFlowExportTimeout: "15s"
  helios-cni.conflist: |
    {
        "cniVersion":"0.3.0",
        "name": "helios",
        "plugins": [
            {
                "type": "helios",
                "ipam": {
                    "type": "host-local"
                }
            },
            {
                "type": "portmap",
                "capabilities": {"portMappings": true}
            },
            {
                "type": "bandwidth",
                "capabilities": {"bandwidth": true}
            }
        ]
    }
  helios-controller.conf: |
    featureGates:    
metadata:
  annotations: {}
  labels:
    app: helios
  name: helios-config-5ct9ktdt77
  namespace: kube-system

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: helios
    component: helios-agent
  name: helios-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: helios
      component: helios-agent
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: helios-agent
      labels:
        app: helios
        component: helios-agent
    spec:
      containers:
      - args:
        - --config
        - /etc/helios/helios-agent.conf
        - --logtostderr=false
        - --log_dir=/var/log/helios
        - --alsologtostderr
        - --log_file_max_size=100
        - --log_file_max_num=4
        - --v=0
        command:
        - helios-agent
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: kongseokhwan/helios/helios:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - container_liveness_probe agent
          failureThreshold: 5
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        name: helios-agent
        ports:
        - containerPort: 10350
          name: api
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            host: localhost
            path: /readyz
            port: api
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 200m
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/helios/helios-agent.conf
          name: helios-config
          readOnly: true
          subPath: helios-agent.conf
        - mountPath: /var/run/helios
          name: host-var-run-helios
        - mountPath: /var/log/helios
          name: host-var-log-helios
        - mountPath: /host/proc
          name: host-proc
          readOnly: true
        - mountPath: /host/var/run/netns
          mountPropagation: HostToContainer
          name: host-var-run-netns
          readOnly: true
        - mountPath: /run/xtables.lock
          name: xtables-lock
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      serviceAccountName: helios-agent
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - configMap:
          name: helios-config-5ct9ktdt77
        name: helios-config
      - hostPath:
          path: /proc
        name: host-proc
      - hostPath:
          path: /var/run/netns
        name: host-var-run-netns
      - hostPath:
          path: /var/run/helios
          type: DirectoryOrCreate
        name: host-var-run-helios
      - hostPath:
          path: /var/log/helios
          type: DirectoryOrCreate
        name: host-var-log-helios
      - hostPath:
          path: /lib/modules
        name: host-lib-modules
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
  updateStrategy:
    type: RollingUpdate
